FROM python:3.12-slim

RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir poetry

WORKDIR /app

#COPY pyproject.toml poetry.lock .env ./
COPY pyproject.toml poetry.lock ./
COPY src/ ./src/

RUN mkdir -p /app/db && chmod -R 777 /app/db

RUN poetry config virtualenvs.create false
RUN poetry install --only main --no-interaction --no-ansi

CMD ["python", "src/main.py"]
